Algoritmo "calculo"

Var
 num1, num2, soma, sub, mult, divi: real
Inicio
escreva("digite o primeiro numero: ")
leia(num1)
escreva("digite o segundo numero: ")
leia(num2)
soma <- num1 + num2
sub <- num1 - num2
mult <- num1 * num2
divi <- num1 / num2
escreval("o resultado da soma é: ",soma)
escreval("o resultado da subtração é: ",sub)
escreval("o resultado da multiplicação é: ",mult)
escreval("o resultado da divisão é: ",divi)

Fimalgoritmo